### ISSUE TITLE
increasing network usage

### ISSUE THREAD

**Issue by fsrv-xyz** [Bryxxit/puppetdb-exporter#3]
I use this exporter on FreeBSD. As written, the exporter will cause an increasing network usage over longer time. See appended graph. After restarting the exporter, network usage will be normal again.

**Comment by fsrv-xyz** [comment]
<img width="1416" alt="scrot0" src="https://user-images.githubusercontent.com/35347506/97104254-a8634580-16b2-11eb-880f-35c55c1135d1.png">

**Comment by negast** [comment]
Hmm maybe the puppet connection to the master or the puppetdb not being properly disconnected? I'll check if that is the issue in the code on Monday

**Comment by negast** [comment]
hmm each cycle I do create a client to both the puppetdb as the master
`go func() {
			for {
				cl := puppetdb.NewClientSSL(c.Host, c.Port, c.Key, c.Cert, c.Ca, false)`

The client itself is from a different repo. But I'm also a  maintainer there so I can fix it if needed. 
I do use a connection without a timeout. I think this may be the issue as idle connections might not be closed properly.

The one I use
`// NewClient returns a http connection for your puppetdb instance.
func NewClient(host string, port int, verbose bool) *Client {

	tr := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}
	client := &http.Client{Transport: tr}
	return &Client{getURL(host, port, false), "", "", client, verbose}
}
`

There is an option to automatically close idle connection with timeouts
`// NewClientTimeout returns a http connection for your puppetdb instance with a timeout.
func NewClientTimeout(host string, port int, verbose bool, timeout int) *Client {

	tr := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}
	client := &http.Client{Transport: tr, Timeout: time.Duration(timeout) * time.Second}
	return &Client{getURL(host, port, false), "", "", client, verbose}
}`
The reason I did not used this Is because sometimes gathering facts takes a while and this can differ per env. But I'll have to test this again.

Maybe the other option could be using the closeIdleConnections functions. Then we would need to allow the httpclient be accessed. I'll test the timeout one first and see if it still runs correctly.

**Comment by negast** [comment]
If added a client_timeout option for the puppetdb part.

https://github.com/Bryxxit/puppetdb-exporter/releases/tag/v1.0.8-beta

You would have to set following param in your yaml
`client_timeout: 10 #is the number of seconds
`

You would have to check if all facts are still collected correctly. I think my env is too small to reach a timeout when collecting. Then you would also have to check wether the connections are still ramping up as fast. I still have to implement a timeout for the master metrics but if this solves it then the issue will be the same.

Alternativelt you could disabel master metrics completly to check.

**Comment by fsrv-xyz** [comment]
Thank you for checking this problems. I will do some tests later today.

**Comment by negast** [comment]
Did it reduce the number of open connections?

**Comment by negast** [comment]
innactive for too long
